//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod3LabE.Platforms.Windows.Strings.en {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mod3LabE.Platforms.Windows.Strings.en.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DatePicker.
        /// </summary>
        internal static string birthDate {
            get {
                return ResourceManager.GetString("birthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate BMI.
        /// </summary>
        internal static string BMI_Button {
            get {
                return ResourceManager.GetString("BMI_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI Calculator.
        /// </summary>
        internal static string BMI_Calculator {
            get {
                return ResourceManager.GetString("BMI Calculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Alcohol.
        /// </summary>
        internal static string Buy_Alcohol {
            get {
                return ResourceManager.GetString("Buy Alcohol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cat Fact.
        /// </summary>
        internal static string Cat_Fact {
            get {
                return ResourceManager.GetString("Cat Fact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click for a Dash.
        /// </summary>
        internal static string DashButton {
            get {
                return ResourceManager.GetString("DashButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click for a Dot.
        /// </summary>
        internal static string DotButton {
            get {
                return ResourceManager.GetString("DotButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A random cat fact will appear here.
        /// </summary>
        internal static string Fact {
            get {
                return ResourceManager.GetString("Fact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your birthday below.
        /// </summary>
        internal static string ForBirthDate {
            get {
                return ResourceManager.GetString("ForBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input.
        /// </summary>
        internal static string In_char {
            get {
                return ResourceManager.GetString("In_char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to enter height in feet:.
        /// </summary>
        internal static string In_heightFeet {
            get {
                return ResourceManager.GetString("In_heightFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to enter height in inches:.
        /// </summary>
        internal static string In_heightInches {
            get {
                return ResourceManager.GetString("In_heightInches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to enter weight in pounds:.
        /// </summary>
        internal static string In_weight {
            get {
                return ResourceManager.GetString("In_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab E Total.
        /// </summary>
        internal static string Lab_E_Total {
            get {
                return ResourceManager.GetString("Lab E Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod3LabE.
        /// </summary>
        internal static string Mod3LabE {
            get {
                return ResourceManager.GetString("Mod3LabE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morse Code.
        /// </summary>
        internal static string Morse_Code {
            get {
                return ResourceManager.GetString("Morse Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can buy alcohol legally in.
        /// </summary>
        internal static string Out_Alcohol {
            get {
                return ResourceManager.GetString("Out_Alcohol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input.
        /// </summary>
        internal static string Out_char {
            get {
                return ResourceManager.GetString("Out_char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See your BMI Calculated!.
        /// </summary>
        internal static string Out_text {
            get {
                return ResourceManager.GetString("Out_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Cat Fact.
        /// </summary>
        internal static string RandomCatFact {
            get {
                return ResourceManager.GetString("RandomCatFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click for a Space.
        /// </summary>
        internal static string SpaceButton {
            get {
                return ResourceManager.GetString("SpaceButton", resourceCulture);
            }
        }
    }
}
